### PR TITLE
Update dependencies to make it compatible with kubernetes 1.22

### LINKED ISSUE #4: Support for k8s 1.22
I had updated a cluster to version 1.22, and found that klum is not able to find resources anymore (was working up to 1.21)

```
time="2021-11-12T17:22:54Z" level=info msg="Starting klum controller"
time="2021-11-12T17:22:54Z" level=fatal msg="the server could not find the requested resource"
```
Is there any roadmap to bring support again for newer kubernetes versions or this project is not anymore into active development?

### PR DESCRIPTION
**Pull request by jadolg**
The current dependencies used in the project are not compatible with kubernetes 1.22.
The changes in this PR are basically updating those dependencies and vendoring them.
A special replacement needed to be done (github.com/rancher/wrangler-api => github.com/dylanhitt/wrangler-api v0.7.0) but it can be removed once https://github.com/rancher/wrangler-api/pull/22 gets merged.
This pr fixes #4 and it was tested with Minikube.

### CODE REVIEW

**Comment by pulpo** [comment]
@ibuildthecloud please take a look at this PR, we really need it! :)

**Comment by DrakeNash** [comment]
@jadolg  this MR can work with upper kubernetes versions?

**Comment by evgenbasharin** [comment]
> @jadolg this MR can work with upper kubernetes versions?

I was able to successfully run it on 1.23.6

**Comment by DrakeNash** [comment]
@ibuildthecloud  please!! attent this MR, the tool it's so useful.

**Pull request merged**
